### ISSUE TITLE
Please distribute a combined license file

### ISSUE THREAD

**Issue by mwoehlke-kitware** [rdeits/meshcat#103]
Currently, the minified `.js`, which contains meshcat plus all of its dependencies rolled into a single file.

Most of these have their own licenses, which typically require giving notice of the license. If the `.min.js` is committed to the repository, it seems that some form of these combined license notices should also be committed.

[license-checker](https://www.npmjs.com/package/license-checker) can be used to locate the relevant license files.

Is meshcat amenable to producing this information and having it committed to the repository?

**Comment by rdeits** [comment]
Let me know if #104 looks like it provides the output you're looking for

**Comment by mwoehlke-kitware** [comment]
That looks like a useful format for web users, maybe not so much if it's showing up on a file system... but I'm not sure Drake's usage should be dictating the format. (It would be nice if @jwnimmer-tri could speak to the "is this what we want" question...)

In the issue referencing this, I [observed](https://github.com/RobotLocomotion/drake/issues/15755#issuecomment-924153620) quite a few more dependencies (as determined by [license-checker](https://www.npmjs.com/package/license-checker)); any thoughts on the difference?

**Comment by jwnimmer-tri** [comment]
> That looks like a useful format for web users, maybe not so much if it's showing up on a file system... but I'm not sure Drake's usage should be dictating the format. (It would be nice if @jwnimmer-tri could speak to the "is this what we want" question...)

It makes sense to me to have the file in meshcat.git use the canonical webpack formatting.

It will be trivial for us to automatically reformat the file as part of the Drake install, if we feel like we need to.

**Comment by rdeits** [comment]
I think this is safe to close. I think the difference is that the set of licenses you found was generated by walking the entire `node_modules` directory, while the set of licenses I'm shipping as of #104 is generated based on only the set of packages which are actually included in the distributed webpack output.
