### ISSUE TITLE
Manipulating parts. How?

### ISSUE THREAD

**Issue by shurko0x4cfd** [rdeits/meshcat#107]
Hello. I have a question. Is there an easy way to manipulate not the whole object, but its parts. For example, I added a structured object (human) to the scene using set_object. I cannot manipulate his hand through the meshcat/human/left_hand path or whatever. How to manipulate individual parts?

**Comment by rdeits** [comment]
I've you've added a single geometry via `set_object`, then meshcat will treat that as a rigid structure, in which case there's no way to move individual parts of the geometry independently. Creating a mechanism with moving parts requires that each component be a separate geometry published with separate `set_object` and `set_transform` calls. As an example, that's how https://github.com/JuliaRobotics/MeshCatMechanisms.jl works: It loads a robot model and then publishes each body independently, allowing them to be moved and animated.

**Comment by shurko0x4cfd** [comment]
Thanks for the answer.
