### ISSUE TITLE
is there a recommended way to record a movie?

### ISSUE THREAD

**Issue by RussTedrake** [rdeits/meshcat#16]

**Comment by rdeits** [comment]
For now, it's just recording the screen with QuickTime or RecordMyDesktop. But I'm planning to eventually add native animation support and rendering to video.

**Comment by rdeits** [comment]
This is coming with #24 and the new animation system support. Basically, the idea is that you'll create an animation in the python bindings (coming soon in https://github.com/rdeits/meshcat-python/pull/15 ) and then the viewer provides a button to record that entire animation. The key is that the recording process is able to play back the animation as slowly as it needs to to *actually* capture every frame, which should make it easy to capture really smooth videos. 

For recording things that aren't actual meshcat animations (like if you're just drawing things in a loop), then Quicktime or RecordMyDesktop will work better.

**Comment by RussTedrake** [comment]
Great!

**Comment by rdeits** [comment]
@RussTedrake  This is now implemented in the python bindings. I haven't tagged a new version yet, but you can install the master branch with: 

```sh
pip install -e git://github.com/rdeits/meshcat-python.git@master#egg=meshcat
```

There's a demo of the whole animation system, with recording, here: https://github.com/rdeits/meshcat-python/blob/master/animation_demo.ipynb  Please give it a shot and let me know if it works for you.
