### ISSUE TITLE
Meshcat server not working

### ISSUE THREAD

**Issue by rickyduh** [rdeits/meshcat#40]
Whenever I run meshcat-server, and navigate to the url, I get an error 404: not sound in the url and these errors:
WARNING:tornado.access:404 GET /static/ (127.0.0.1) 1.24ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.32ms
WARNING:tornado.access:404 GET /static/ (127.0.0.1) 0.65ms
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.34ms
in my terminal. Any advice ?

**Comment by rdeits** [comment]
I think this is an issue with the Python bindings, so I'm going to close this issue in favor of https://github.com/rdeits/meshcat-python/issues/30
