### ISSUE TITLE
Moving the camera location with mouse?

### ISSUE THREAD

**Issue by danieljfarrell** [rdeits/meshcat#47]
Firstly, thank you for such an amazing project. It is exactly what I was looking for doing visualisation of ray-tracing (open source python). I'm going to build the visualiser part of the code around meshcat.

Clicking and dragging in the browser window rotates the camera around it's origin. It is possible to also change the origin point of the camera using the mouse with a keyboard combination pressed?

**Comment by rdeits** [comment]
Try right-clicking and dragging with the mouse. Does that do what you're looking for?

**Comment by danieljfarrell** [comment]
I tried a few combinations, i’ll try again, but nothing seemed to rotate the camera. Will report back ...

**Comment by danieljfarrell** [comment]
It seems on a Mac track pad, holding ‘Ctrl’ and moving the mouse (which is normal a right click) doesn’t not work. You have to use two fingers.
