### ISSUE TITLE
Make background color configurable

### ISSUE THREAD

**Issue by rdeits** [rdeits/meshcat#52]
It's currently hard-coded here: 

https://github.com/rdeits/meshcat/blob/efc157436ca4abf5706cf248c51d2e86cae1a0f0/src/index.js#L531-L532

but it would be easy to make this configurable through the GUI.

**Comment by rdeits** [comment]
cc @thowell

**Comment by GathererA** [comment]
Hello! I've changed the top_color manually in the source code locally on my machine, but nothing changes. I'm currently using the Julia wrapper. I have tried various combinations of colors, but no set will change from lightskyblue and midnightblue. Is there something else that I should be doing to re-implement the javascript code in the Julia wrapper? 

Thanks!

**Comment by GathererA** [comment]
Got it! The accessed hardcoded colors are not in the index.js file but rather the main.min.js file.

**Comment by tkoolen** [comment]
The `main.min.js` file is generated from the `index.js` file. See https://github.com/rdeits/meshcat#developing-meshcat.

**Comment by RussTedrake** [comment]
I believe this was resolved by #72.
