### ISSUE TITLE
Fetching resources via URL

### ISSUE THREAD

**Issue by VladimirIvan** [rdeits/meshcat#56]
I would like to add support for loading meshes/textures/materials form a url, including fetching dependent resources (e.g., textures for dae meshes).

The `ExtensibleObjectLoader` is currently loading meshes using the synchroneous `parse` method and returns the geometry. Is there a reason why the asynchronous `load` method is not used? Would it be ok to make all the loading asynchroneous (using the `onLoad` callback) in a similar way the `load` method is implemented?

**Comment by VladimirIvan** [comment]
#58 and #54 implement this feature without the need to use the async features.
Can be closed when #58 gets merged.

**Comment by rdeits** [comment]
Closing since #58 is in
