### ISSUE TITLE
Missing/Incorrect mesh material

### ISSUE THREAD

**Issue by ferrolho** [rdeits/meshcat#59]
### Screenshots

Expected behaviour (last working on dd1dc106cb713b4182a15eaf758e2ba98bcdefc5)

![Screenshot from 2019-08-02 21-21-57](https://user-images.githubusercontent.com/4166093/62398138-c3a6da00-b56f-11e9-9613-10bdf8167233.png)

Current behaviour (from 0eee0da6c5220f1e97719b4568c94788f9ba56c5 onwards)

![Screenshot from 2019-08-02 21-42-24](https://user-images.githubusercontent.com/4166093/62398144-c5709d80-b56f-11e9-852c-ad81684f495a.png)

### Reproducible Code

```julia
using Colors
using MeshCat
using Polyhedra
using QHull

vis = Visualizer()
open(vis)

v1 = [1 1 1 1 0 0 0 0
      1 1 0 0 1 1 0 0
      1 0 1 0 1 0 1 0.]'

p1 = polyhedron(vrep(v1), QHull.Library())

m1 = Polyhedra.Mesh(p1)

material = MeshPhongMaterial(color=RGBA(1, 1, 1, 1))

setobject!(vis[:m1], m1, material)
```

---

I am using https://github.com/rdeits/MeshCat.jl (master branch [`d1bec32`](d1bec321d8f85bb2405e927bcd34a24061e77e87)) and setting the `meshcat` version to be used in https://github.com/rdeits/MeshCat.jl/blob/master/deps/build.jl#L5.

I incorrectly opened an issue in https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/180 concerning this.

**Comment by rdeits** [comment]
Thanks for the bug report! I've just fixed this on the javascript side, and I'll include it with the next MeshCat.jl release.

**Comment by ferrolho** [comment]
Thanks, Robin! :smiley:
