### ISSUE TITLE
Tagging versions

### ISSUE THREAD

**Issue by TheCynosure** [rdeits/meshcat#92]
I would like to use meshcat but I need a tagged release to be able to use it. Is it possible that you could tag HEAD with a minor release number so that I can use it easily? Thanks!

**Comment by rdeits** [comment]
Yup, will do, as soon as I've resolved https://github.com/rdeits/meshcat/pull/95

**Comment by rdeits** [comment]
Done: https://github.com/rdeits/meshcat/releases/tag/v0.1.0
